server:
  port: 8081
spring:
  application:
    name:  DemoTracingService

management:
  endpoints:
    web:
      exposure:
        include: health
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
